### ISSUE TITLE
Instantiate client once, instead of once / request

### ISSUE THREAD

**Issue by mbryzek** [gilt/apidoc#206]
Right now, in order to pass in a basic auth token, have to create a new client instance. Better would be to have a singleton client and initiate a request passing in the token

**Comment by grahamar** [comment]
+1

Nova ran into a perfect-day issue on Friday which was due to the creation of a client instance per user request. It was noted that we used to have this issue before the commons client factory pattern was implemented. Also to note this is the 3rd time this has happened, with an apidoc client, in as many months.

Either a way to pass in the async http client to the apidoc client at creation or a singleton client with an optional list of headers per request would mean this is at least much more obvious for users of apidoc clients.

**Comment by RoryH** [comment]
+1

**Comment by haywood** [comment]
I don't have full background on the other resources that ning may create under the hood, but [this PR](https://github.com/gilt/apidoc/pull/281) likely mitigates this issue.

**Comment by grahamar** [comment]
I don't know enough about ning to know if that would be enough to fix it for us... I think passing in the entire `AsyncHttpClient` or at least `AsyncHttpClientConfig` would be better, giving users the ability to create SSL clients that use their own certificates, would be just one benefit. http://sonatype.github.io/async-http-client/ssl.html

**Comment by emersonloureiro** [comment]
+1 to this.

A quick, and probably easy enough fix, would be to make the ```AsyncHttpClient``` used by the apidoc-generated client a singleton. This way, even if you create multiple apidoc clients, the underlying async client will still be a singleton.

**Comment by mbryzek** [comment]
This change is in production - the async http client is now a parameter when instantiating the client, and it defaults to a singleton.
