### ISSUE TITLE
Parameter requirements in GET/PATCH

### ISSUE THREAD

**Issue by haywood** [gilt/apidoc#264]
I think it would be really nice if parameters in apidoc defaulted to "required: false" for GET and PATCH.

**Comment by mbryzek** [comment]
on the 222-union-types branch, experimenting with removing the required flag altogether in favor of "option[xxx]" syntax in the type. curious what you think about this approach?

**Comment by romusz** [comment]
looks to me as a Scalaism that will rather stick out (and I like Scala) - it doesn't have the json 'feel' to.

**Comment by mbryzek** [comment]
thanks!

what do you think about haywood's idea to change the default for 'required' depending on context? It is true that we almost always have to write "required": false when using parameters so I kind of like the idea of implementing his suggestion

**Comment by romusz** [comment]
context-dependent defaults are quite hard decision - it may surprise people, even though there's a method to this madness. The biggest concern is that if somebody new to apidoc will look at api.json w/o the prior knowledge, they are not likely to guess that the default depends on the context (leading to confusion). Also I wouldn't be surprised if somebody decided to defensively specify `required` attribute always since they don't want to be sensitive to context-dependent defaults (this would lead to more 'noise' than there is now). So I'm on the fence on this one. If I were building apidoc for myself, I'd go for it - to me it's logical and easy to remember, but apidoc is, I think, supposed to be a tool for 'masses' (no pejorative meaning here) hence the hesitation.

**Comment by mbryzek** [comment]
Based on conversation - going to leave as is (required option always defaults to true)
