### ISSUE TITLE
Generated Play routes in wrong order.

### ISSUE THREAD

**Issue by khy** [gilt/apidoc#268]
Was working with the generated code from this spec: http://www.apidoc.me/gilt/system-account-audit/0.9.8

It generated the following Play 2.x routes file segment:
```
GET      /employees/:id                           controllers.Employees.getById(id: Long)
GET      /employees                               controllers.Employees.get(text: scala.Option[String], has_system_of_record_id: scala.Option[Boolean], is_terminated: scala.Option[Boolean], limit: Int ?= 50, offset: Int ?= 0)
# Additional parameters to GET /employees
#   - organization_ids: scala.Option[Seq[Long]]
#   - system_ids: scala.Option[Seq[Long]]
#   - emails: scala.Option[Seq[String]]
#   - usernames: scala.Option[Seq[String]]
GET      /employees/imports                       controllers.Employees.getImports(limit: Int ?= 50, offset: Int ?= 0)
```
This is problematic because the more generic `/employees/:id` comes before the more specific `/employees/imports`, meaning that hitting the `/employees/imports` URL returns a Bad Request ("imports" cannot be parsed as Long).

**Comment by mbryzek** [comment]
So it turns out that:

  - the operations in api.json are an array
  - in apidoc, we don't try to sort or do anything other than iterate through operations and create routes

that means that to avoid this particular problem, simply reorder your api.json file so the /employees/imports path appears before the /employees/:id path
